// const mongoose = require("mongoose");

// //define a tag schema for the database
// const TagSchema = new mongoose.Schema({
//   parent: String, // links to the _id of a parent event (_id is an autogenerated field by Mongoose).
//   content: String,
// });

// // compile model from schema
// module.exports = mongoose.model("tag", TagSchema);